#include "board_port.h"

/* Logical gray sensor bits used by the line-follow algorithm. */
#define BIT_SENSOR_L2 (1U << 0)
#define BIT_SENSOR_L1 (1U << 1)
#define BIT_SENSOR_C  (1U << 2)
#define BIT_SENSOR_R1 (1U << 3)
#define BIT_SENSOR_R2 (1U << 4)

/* PWM symbols generated by SysConfig. Override these macros if SysConfig names
 * are changed later.
 */
#ifndef LEFT_PWM_INST
#define LEFT_PWM_INST PWM_0_INST
#endif

#ifndef LEFT_PWM_CC_INDEX
#define LEFT_PWM_CC_INDEX DL_TIMER_CC_0_INDEX
#endif

#ifndef RIGHT_PWM_INST
#define RIGHT_PWM_INST PWM_0_INST
#endif

#ifndef RIGHT_PWM_CC_INDEX
#define RIGHT_PWM_CC_INDEX DL_TIMER_CC_1_INDEX
#endif

#if SERVO_PWM_ENABLE
#ifndef SERVO_PWM_INST
#error "SERVO_PWM_ENABLE=1 时必须定义 SERVO_PWM_INST"
#endif

#ifndef SERVO_PWM_CC_INDEX
#error "SERVO_PWM_ENABLE=1 时必须定义 SERVO_PWM_CC_INDEX"
#endif
#endif

#if (GRAY_SAMPLE_COUNT == 0U) || ((GRAY_SAMPLE_COUNT % 2U) == 0U)
#error "GRAY_SAMPLE_COUNT must be a non-zero odd number"
#endif

/* Write PWM duty to one timer channel.
 * Important: duty 0 is forced to compare 0 so stop really means stop even when
 * the board uses inverted compare logic.
 */
static void set_pwm_duty(GPTIMER_Regs *timer, DL_TIMER_CC_INDEX cc_index, uint16_t duty)
{
    uint16_t compare_value;

    if (duty == 0U) {
        DL_TimerG_setCaptureCompareValue(timer, 0U, cc_index);
        return;
    }

    if (duty > MOTOR_PWM_PERIOD_COUNTS) {
        duty = MOTOR_PWM_PERIOD_COUNTS;
    }

#if MOTOR_PWM_COMPARE_IS_INVERTED
    compare_value = MOTOR_PWM_PERIOD_COUNTS - duty;
#else
    compare_value = duty;
#endif

    DL_TimerG_setCaptureCompareValue(timer,
                                     compare_value,
                                     cc_index);
}

/* 输出舵机脉宽。
 *
 * 舵机使用 50Hz PWM：周期 20ms，高电平通常 1000~2000us。
 * 注意：电机 PWM 周期很短，不能直接拿电机 PWM 通道驱动舵机。
 *
 * pulse_us 是“高电平持续时间”，不是占空比百分比：
 *   pulse_us = 1500 表示 20ms 周期里高电平 1.5ms。
 *
 * 如果 SERVO_PWM_TIMER_CLK_HZ = 1000000，则 1 tick = 1us，
 * pulse_us 可以直接换算成 compare ticks。
 *
 * 如果 SysConfig 生成的是反相 PWM，就把 SERVO_PWM_COMPARE_IS_INVERTED
 * 置 1，这样 compare 会自动用 period - ticks。
 */
static void set_water_pipe_servo_pulse_us(uint16_t pulse_us)
{
#if SERVO_PWM_ENABLE
    /* 这个PWM只控制水管SG90；小车电机PWM仍由TIMG0独立输出。 */
    if (pulse_us < SERVO_PWM_SAFE_MIN_PULSE_US) {
        pulse_us = SERVO_PWM_SAFE_MIN_PULSE_US;
    } else if (pulse_us > SERVO_PWM_SAFE_MAX_PULSE_US) {
        pulse_us = SERVO_PWM_SAFE_MAX_PULSE_US;
    }

    /* us 转定时器计数值。加 500000 是为了做四舍五入，避免低频时误差偏大。 */
    uint32_t ticks = ((uint32_t) pulse_us * SERVO_PWM_TIMER_CLK_HZ +
                      500000U) / 1000000U;
    uint32_t compare_value;

    if (ticks > SERVO_PWM_PERIOD_COUNTS) {
        ticks = SERVO_PWM_PERIOD_COUNTS;
    }

#if SERVO_PWM_COMPARE_IS_INVERTED
    compare_value = SERVO_PWM_PERIOD_COUNTS - ticks;
#else
    compare_value = ticks;
#endif

    DL_TimerA_setCaptureCompareValue(SERVO_PWM_INST,
                                     (uint16_t) compare_value,
                                     SERVO_PWM_CC_INDEX);
    /* IO表里PB0/C0和PB1/C1都标为舵机输出，所以两个通道写入相同脉宽。
     * 舵机信号线接其中任意一个接口，得到的控制波形都相同。
     */
    DL_TimerA_setCaptureCompareValue(SERVO_PWM_INST,
                                     (uint16_t) compare_value,
                                     SERVO_PWM_ALT_CC_INDEX);
#else
    /* 还没有配置舵机 PWM 硬件时，保留空实现，方便先编译和写上层算法。 */
    (void) pulse_us;
#endif
}

/* TB6612 A channel direction. Logical forward is corrected in main.c. */
static void set_left_direction(bool forward)
{
    if (forward) {
        DL_GPIO_setPins(MOTOR_AIN1_PORT, MOTOR_AIN1_PIN);
        DL_GPIO_clearPins(MOTOR_AIN2_PORT, MOTOR_AIN2_PIN);
    } else {
        DL_GPIO_clearPins(MOTOR_AIN1_PORT, MOTOR_AIN1_PIN);
        DL_GPIO_setPins(MOTOR_AIN2_PORT, MOTOR_AIN2_PIN);
    }
}

/* TB6612 B channel direction. Logical forward is corrected in main.c. */
static void set_right_direction(bool forward)
{
    if (forward) {
        DL_GPIO_setPins(MOTOR_BIN1_PORT, MOTOR_BIN1_PIN);
        DL_GPIO_clearPins(MOTOR_BIN2_PORT, MOTOR_BIN2_PIN);
    } else {
        DL_GPIO_clearPins(MOTOR_BIN1_PORT, MOTOR_BIN1_PIN);
        DL_GPIO_setPins(MOTOR_BIN2_PORT, MOTOR_BIN2_PIN);
    }
}

/* Configure all possible start keys used on this car: A07, B10, B14, B11. */
static void init_start_button(void)
{
    DL_GPIO_initDigitalInputFeatures(START_BUTTON_IOMUX,
        DL_GPIO_INVERSION_DISABLE, DL_GPIO_RESISTOR_PULL_UP,
        DL_GPIO_HYSTERESIS_DISABLE, DL_GPIO_WAKEUP_DISABLE);
    DL_GPIO_initDigitalInputFeatures(IOMUX_PINCM27,
        DL_GPIO_INVERSION_DISABLE, DL_GPIO_RESISTOR_PULL_UP,
        DL_GPIO_HYSTERESIS_DISABLE, DL_GPIO_WAKEUP_DISABLE);
    DL_GPIO_initDigitalInputFeatures(IOMUX_PINCM31,
        DL_GPIO_INVERSION_DISABLE, DL_GPIO_RESISTOR_PULL_UP,
        DL_GPIO_HYSTERESIS_DISABLE, DL_GPIO_WAKEUP_DISABLE);
    DL_GPIO_initDigitalInputFeatures(IOMUX_PINCM28,
        DL_GPIO_INVERSION_DISABLE, DL_GPIO_RESISTOR_PULL_UP,
        DL_GPIO_HYSTERESIS_DISABLE, DL_GPIO_WAKEUP_DISABLE);
}

void Board_init(void)
{
    SYSCFG_DL_init();
    init_start_button();
    Board_setBuzzer(false);

#ifdef MOTOR_STBY_PIN
    DL_GPIO_setPins(MOTOR_STBY_PORT, MOTOR_STBY_PIN);
#endif

    DL_TimerG_startCounter(LEFT_PWM_INST);
    if (LEFT_PWM_INST != RIGHT_PWM_INST) {
        DL_TimerG_startCounter(RIGHT_PWM_INST);
    }

    Board_setServoPulseUs(SERVO_PWM_CENTER_PULSE_US);
#if SERVO_PWM_ENABLE
    DL_TimerA_startCounter(SERVO_PWM_INST);
#endif

    /* 100 Hz control loop: one control update every 10 ms. */
    SysTick->LOAD  = (CPUCLK_FREQ / 100U) - 1U;
    SysTick->VAL   = 0U;
    SysTick->CTRL  = SysTick_CTRL_CLKSOURCE_Msk |
                     SysTick_CTRL_TICKINT_Msk |
                     SysTick_CTRL_ENABLE_Msk;
    NVIC_EnableIRQ(SysTick_IRQn);
}

/* Read gray sensors once and map physical sensor order to logical L2..R2.
 * The real car gray board is reversed, so L/R are intentionally swapped here.
 */
static uint8_t read_gray5_once(void)
{
    uint8_t bits = 0;

#if GRAY_BLACK_IS_LOW
    if ((DL_GPIO_readPins(GRAY_L2_PORT, GRAY_L2_PIN) & GRAY_L2_PIN) == 0U) { bits |= BIT_SENSOR_R2; }
    if ((DL_GPIO_readPins(GRAY_L1_PORT, GRAY_L1_PIN) & GRAY_L1_PIN) == 0U) { bits |= BIT_SENSOR_R1; }
    if ((DL_GPIO_readPins(GRAY_C_PORT, GRAY_C_PIN) & GRAY_C_PIN) == 0U) { bits |= BIT_SENSOR_C; }
    if ((DL_GPIO_readPins(GRAY_R1_PORT, GRAY_R1_PIN) & GRAY_R1_PIN) == 0U) { bits |= BIT_SENSOR_L1; }
    if ((DL_GPIO_readPins(GRAY_R2_PORT, GRAY_R2_PIN) & GRAY_R2_PIN) == 0U) { bits |= BIT_SENSOR_L2; }
#else
    if ((DL_GPIO_readPins(GRAY_L2_PORT, GRAY_L2_PIN) & GRAY_L2_PIN) != 0U) { bits |= BIT_SENSOR_R2; }
    if ((DL_GPIO_readPins(GRAY_L1_PORT, GRAY_L1_PIN) & GRAY_L1_PIN) != 0U) { bits |= BIT_SENSOR_R1; }
    if ((DL_GPIO_readPins(GRAY_C_PORT, GRAY_C_PIN) & GRAY_C_PIN) != 0U) { bits |= BIT_SENSOR_C; }
    if ((DL_GPIO_readPins(GRAY_R1_PORT, GRAY_R1_PIN) & GRAY_R1_PIN) != 0U) { bits |= BIT_SENSOR_L1; }
    if ((DL_GPIO_readPins(GRAY_R2_PORT, GRAY_R2_PIN) & GRAY_R2_PIN) != 0U) { bits |= BIT_SENSOR_L2; }
#endif

    return bits;
}

/* Majority filter for gray sensors. With GRAY_SAMPLE_COUNT=3, at least two
 * samples must agree before a bit is accepted.
 */
uint8_t Board_readGray5(void)
{
    uint8_t counts[5] = {0};
    uint8_t bits = 0;

    for (uint8_t sample = 0; sample < GRAY_SAMPLE_COUNT; sample++) {
        uint8_t raw_bits = read_gray5_once();

        for (uint8_t bit = 0; bit < 5U; bit++) {
            if ((raw_bits & (1U << bit)) != 0U) {
                counts[bit]++;
            }
        }

#if GRAY_SAMPLE_INTERVAL_CYCLES > 0U
        if (sample + 1U < GRAY_SAMPLE_COUNT) {
            delay_cycles(GRAY_SAMPLE_INTERVAL_CYCLES);
        }
#endif
    }

    for (uint8_t bit = 0; bit < 5U; bit++) {
        if (counts[bit] > (GRAY_SAMPLE_COUNT / 2U)) {
            bits |= (uint8_t) (1U << bit);
        }
    }

    return bits;
}

static uint16_t speed_to_duty(int16_t speed)
{
    int32_t duty = speed;

    if (duty < 0) {
        duty = -duty;
    }
    if (duty > (int32_t) MOTOR_PWM_PERIOD_COUNTS) {
        duty = MOTOR_PWM_PERIOD_COUNTS;
    }

    return (uint16_t) duty;
}

/* Low-level motor output. Positive/negative means channel direction, absolute
 * value means PWM duty. A zero command clears both direction pins to coast/stop.
 */
void Board_setMotorSpeed(int16_t left_speed, int16_t right_speed)
{
    bool left_forward = (left_speed >= 0);
    bool right_forward = (right_speed >= 0);
    uint16_t left_duty = speed_to_duty(left_speed);
    uint16_t right_duty = speed_to_duty(right_speed);

    if (left_duty == 0U) {
        DL_GPIO_clearPins(MOTOR_AIN1_PORT, MOTOR_AIN1_PIN);
        DL_GPIO_clearPins(MOTOR_AIN2_PORT, MOTOR_AIN2_PIN);
    } else {
        set_left_direction(left_forward);
    }

    if (right_duty == 0U) {
        DL_GPIO_clearPins(MOTOR_BIN1_PORT, MOTOR_BIN1_PIN);
        DL_GPIO_clearPins(MOTOR_BIN2_PORT, MOTOR_BIN2_PIN);
    } else {
        set_right_direction(right_forward);
    }

    set_pwm_duty(LEFT_PWM_INST, LEFT_PWM_CC_INDEX, left_duty);
    set_pwm_duty(RIGHT_PWM_INST, RIGHT_PWM_CC_INDEX, right_duty);
}

void Board_setServoPulseUs(uint16_t pulse_us)
{
    /* 板级舵机输出入口。
     * 上层 servo_control.c 只关心“我要输出多少 us”，不直接碰定时器寄存器。
     * 这样以后换舵机引脚或定时器，只需要改 board_port 这一层。
     */
    set_water_pipe_servo_pulse_us(pulse_us);
}

/* Any configured key can start/stop the car. Keys are treated as active low. */
bool Board_readStartButton(void)
{
    uint32_t key_a7  = DL_GPIO_readPins(GPIOA, DL_GPIO_PIN_7) & DL_GPIO_PIN_7;
    uint32_t key_b10 = DL_GPIO_readPins(GPIOB, DL_GPIO_PIN_10) & DL_GPIO_PIN_10;
    uint32_t key_b14 = DL_GPIO_readPins(GPIOB, DL_GPIO_PIN_14) & DL_GPIO_PIN_14;
    uint32_t key_b11 = DL_GPIO_readPins(GPIOB, DL_GPIO_PIN_11) & DL_GPIO_PIN_11;

#if START_BUTTON_ACTIVE_LOW
    return (key_a7 == 0U) || (key_b10 == 0U) ||
           (key_b14 == 0U) || (key_b11 == 0U);
#else
    return (key_a7 != 0U) || (key_b10 != 0U) ||
           (key_b14 != 0U) || (key_b11 != 0U);
#endif
}

bool Board_readTaskKey(uint8_t key_id)
{
    uint32_t pin_state = 1U;

    switch (key_id) {
    case 1U:
        pin_state = DL_GPIO_readPins(GPIOA, DL_GPIO_PIN_7) & DL_GPIO_PIN_7;
        break;
    case 2U:
        pin_state = DL_GPIO_readPins(GPIOB, DL_GPIO_PIN_10) & DL_GPIO_PIN_10;
        break;
    case 3U:
        pin_state = DL_GPIO_readPins(GPIOB, DL_GPIO_PIN_14) & DL_GPIO_PIN_14;
        break;
    case 4U:
        pin_state = DL_GPIO_readPins(GPIOB, DL_GPIO_PIN_11) & DL_GPIO_PIN_11;
        break;
    default:
        return false;
    }

#if START_BUTTON_ACTIVE_LOW
    return pin_state == 0U;
#else
    return pin_state != 0U;
#endif
}

void Board_setBuzzer(bool on)
{
#if BEEP_ACTIVE_LOW
    if (on) {
        DL_GPIO_clearPins(BEEP_PORT, BEEP_PIN);
    } else {
        DL_GPIO_setPins(BEEP_PORT, BEEP_PIN);
    }
#else
    if (on) {
        DL_GPIO_setPins(BEEP_PORT, BEEP_PIN);
    } else {
        DL_GPIO_clearPins(BEEP_PORT, BEEP_PIN);
    }
#endif
}

void Board_setStatusLed(bool on)
{
#if STATUS_LED_ENABLE
    if (on) {
        DL_GPIO_setPins(STATUS_LED_PORT, STATUS_LED_PIN);
    } else {
        DL_GPIO_clearPins(STATUS_LED_PORT, STATUS_LED_PIN);
    }
#else
    (void) on;
#endif
}

void Board_delayMs(uint32_t ms)
{
    while (ms-- > 0U) {
        delay_cycles(CPUCLK_FREQ / 1000U);
    }
}

